{
  parserClass="com.intellij.idea.plugin.hybris.impex.ImpexParser"
  parserUtilClass="com.intellij.idea.plugin.hybris.impex.ImpexParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Impex"
  psiImplClassSuffix="Impl"
  psiPackage="com.intellij.idea.plugin.hybris.impex.psi"
  psiImplPackage="com.intellij.idea.plugin.hybris.impex.psi.impl"

  elementTypeHolderClass="com.intellij.idea.plugin.hybris.impex.psi.ImpexTypes"
  elementTypeClass="com.intellij.idea.plugin.hybris.impex.psi.ImpexElementType"
  tokenTypeClass="com.intellij.idea.plugin.hybris.impex.psi.ImpexTokenType"

//  psiImplUtilClass="com.intellij.idea.plugin.hybris.impex.psi.impl.ImpexPsiImplUtil"
}

//impexFile ::= item_*
//private item_ ::= (property|COMMENT|CRLF)
//property ::= (KEY? SEPARATOR VALUE?) | KEY {methods=[getKey getValue]}

impexFile ::= item_*
private item_ ::= (CRLF|COMMENT|MACRO_DECLARATION|ASSIGN_VALUE|HEADER_MODE_INSERT|HEADER_MODE_UPDATE|HEADER_MODE_INSERT_UPDATE|HEADER_MODE_REMOVE|HEADER_TYPE|VALUE_SUBTYPE|FIELD_VALUE_SEPARATOR|FIELD_LIST_ITEM_SEPARATOR|FIELD_VALUE|SINGLE_STRING|DOUBLE_STRING|FIELD_VALUE_IGNORE)
