{
  parserClass="com.intellij.idea.plugin.hybris.impex.ImpexParser"
  parserUtilClass="com.intellij.idea.plugin.hybris.impex.util.ImpexParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Impex"
  psiImplClassSuffix="Impl"
  psiPackage="com.intellij.idea.plugin.hybris.impex.psi"
  psiImplPackage="com.intellij.idea.plugin.hybris.impex.psi.impl"

  elementTypeHolderClass="com.intellij.idea.plugin.hybris.impex.psi.ImpexTypes"
  elementTypeClass="com.intellij.idea.plugin.hybris.impex.psi.ImpexElementType"
  tokenTypeClass="com.intellij.idea.plugin.hybris.impex.psi.ImpexTokenType"

  psiImplUtilClass="com.intellij.idea.plugin.hybris.impex.util.ImpexPsiImplUtil"
}

//impexFile ::= item_*
//private item_ ::= (property|COMMENT|CRLF)
//property ::= (KEY? SEPARATOR VALUE?) | KEY {methods=[getKey getValue]}

impexFile ::= item*

private item ::= (any)

modifiers_block ::= LEFT_SQUARE_BRACKET other * RIGHT_SQUARE_BRACKET

parameters_block ::= LEFT_ROUND_BRACKET any *  RIGHT_ROUND_BRACKET

private any ::= (other | parameters_block | modifiers_block)

private other ::= (CRLF|COMMENT_MARKER|COMMENT_BODY|MACRO_DECLARATION|ASSIGN_VALUE|HEADER_MODE_INSERT|HEADER_MODE_UPDATE|HEADER_MODE_INSERT_UPDATE|HEADER_MODE_REMOVE|HEADER_TYPE|VALUE_SUBTYPE|FIELD_VALUE_SEPARATOR|FIELD_LIST_ITEM_SEPARATOR|FIELD_VALUE|SINGLE_STRING|DOUBLE_STRING|FIELD_VALUE_IGNORE|BEAN_SHELL_MARKER|BEAN_SHELL_BODY|ATTRIBUTE_NAME|ATTRIBUTE_VALUE|ATTRIBUTE_SEPARATOR|BOOLEAN|DIGIT|CLASS_WITH_PACKAGE|MACRO_VALUE|ALTERNATIVE_MAP_DELIMITER|DEFAULT_KEY_VALUE_DELIMITER|DEFAULT_PATH_DELIMITER|HEADER_PARAMETER_NAME|COMMA|SEMICOLON|PARAMETERS_SEPARATOR|HEADER_SPECIAL_PARAMETER_NAME|MACRO_USAGE|ALTERNATIVE_PATTERN|DOCUMENT_ID)

