/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

/*
 * This file is part of "hybris integration" plugin for Intellij IDEA.
 * Copyright (C) 2014-2016 Alexander Bartash <AlexanderBartash@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package com.intellij.idea.plugin.hybris.flexibleSearch;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import com.intellij.psi.TokenType;
import com.intellij.psi.JavaTokenType;

import static com.intellij.psi.TokenType.WHITE_SPACE;
import static com.intellij.idea.plugin.hybris.flexibleSearch.psi.FlexibleSearchTypes.*;
import static com.intellij.idea.plugin.hybris.flexibleSearch.FlexibleSearchParserDefinition.COMMENT;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>flexibleSearch.flex</tt>
 */
public class FlexibleSearchLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [12, 6, 3]
   * Total runtime size is 15472 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>9]<<6)|((ch>>3)&0x3f)]<<3)|(ch&0x7)];
  }

  /* The ZZ_CMAP_Z table has 2176 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1"+
    "\20\5\21\1\22\1\23\1\24\1\21\14\25\1\26\50\25\1\27\2\25\1\30\1\31\1\32\1\33"+
    "\25\25\1\34\20\21\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\21\1\44\1\45\1\46\1"+
    "\21\1\47\1\50\1\51\1\52\1\53\3\21\1\25\1\54\1\55\5\21\2\25\1\56\31\21\1\25"+
    "\1\57\1\21\1\60\40\21\1\61\17\21\1\62\1\63\1\64\1\65\13\21\1\66\10\21\123"+
    "\25\1\67\7\25\1\70\1\71\37\21\1\25\1\71\u0582\21\1\72\u017f\21");

  /* The ZZ_CMAP_Y table has 3776 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\0\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\7\1\10\1\11\1\13\1\14"+
    "\3\0\1\15\1\16\1\17\1\20\2\21\1\22\3\21\1\22\7\21\1\23\10\21\1\24\50\21\1"+
    "\25\1\21\1\26\1\27\1\30\1\31\2\27\16\0\1\32\1\33\1\34\1\35\2\21\1\36\11\21"+
    "\1\37\21\21\1\40\1\41\23\21\1\27\1\42\3\21\1\22\1\43\1\42\4\21\1\44\1\45\4"+
    "\0\1\46\1\47\1\27\3\21\2\50\1\27\1\51\1\52\1\0\1\53\5\21\1\54\2\0\1\5\1\55"+
    "\1\56\13\21\1\57\1\46\1\60\1\61\1\5\1\62\1\27\1\63\1\64\3\21\3\0\1\65\12\21"+
    "\1\66\1\0\1\67\1\27\1\5\1\70\3\21\1\54\1\71\1\20\2\21\1\66\1\72\1\73\1\74"+
    "\2\27\3\21\1\75\10\27\1\76\1\30\6\27\1\77\2\0\1\100\1\101\6\21\1\102\2\0\1"+
    "\103\1\21\1\104\1\5\2\42\1\105\1\106\1\107\2\21\1\76\1\110\1\111\1\112\1\113"+
    "\1\63\1\114\1\104\1\5\1\115\1\52\1\105\1\116\1\107\2\21\1\76\1\117\1\120\1"+
    "\121\1\122\1\123\1\124\1\125\1\5\1\126\1\27\1\105\1\37\1\36\2\21\1\76\1\127"+
    "\1\111\1\46\1\130\1\131\1\27\1\104\1\5\1\43\1\27\1\105\1\106\1\107\2\21\1"+
    "\76\1\127\1\111\1\112\1\122\1\132\1\114\1\104\1\5\1\43\1\27\1\133\1\134\1"+
    "\135\1\136\1\137\1\134\1\21\1\140\1\141\1\142\1\143\1\27\1\125\1\5\1\27\1"+
    "\43\1\105\1\32\1\76\2\21\1\76\1\144\1\145\1\146\1\142\1\147\1\26\1\104\1\5"+
    "\2\27\1\150\1\32\1\76\2\21\1\76\1\144\1\111\1\146\1\142\1\147\1\34\1\104\1"+
    "\5\1\151\1\27\1\150\1\32\1\76\4\21\1\152\1\146\1\153\1\63\1\27\1\104\1\5\1"+
    "\27\1\41\1\150\1\21\1\22\1\41\2\21\1\36\1\154\1\22\1\155\1\156\1\0\1\157\1"+
    "\160\1\161\1\27\1\42\5\21\1\162\1\163\1\164\1\100\1\5\1\165\4\27\1\166\1\167"+
    "\1\170\1\42\1\171\1\172\1\162\1\173\1\174\1\175\1\5\1\176\4\27\1\131\2\27"+
    "\1\177\1\5\1\165\1\200\1\201\1\21\1\42\3\21\1\30\1\45\1\0\1\146\1\202\1\0"+
    "\1\45\3\0\1\51\1\203\7\27\5\21\1\54\1\0\1\204\1\5\1\165\1\66\1\205\1\206\1"+
    "\207\1\210\1\21\1\211\1\212\1\5\1\213\4\21\1\37\1\17\5\21\1\214\51\21\1\135"+
    "\1\22\1\135\5\21\1\135\4\21\1\135\1\22\1\135\1\21\1\22\7\21\1\135\10\21\1"+
    "\215\4\27\2\21\2\27\12\21\1\30\1\27\1\42\114\21\1\106\2\21\1\216\2\21\1\50"+
    "\11\21\1\134\1\131\1\27\1\21\1\32\1\217\1\27\2\21\1\217\1\27\2\21\1\220\1"+
    "\27\1\21\1\32\1\221\1\27\6\21\1\222\3\0\1\223\1\224\1\5\1\165\3\27\1\225\1"+
    "\5\1\165\13\21\1\27\5\21\1\226\10\21\1\227\1\27\3\21\1\30\1\0\1\2\1\0\1\2"+
    "\1\125\1\5\3\21\1\227\1\30\1\27\5\21\1\115\2\0\1\56\1\177\1\5\1\165\4\27\2"+
    "\21\1\164\1\2\6\21\1\202\1\100\3\0\1\112\1\5\1\165\1\5\1\165\1\44\13\27\1"+
    "\230\5\21\1\222\1\0\1\230\1\115\1\5\1\165\1\27\1\231\1\2\1\27\1\232\3\21\1"+
    "\103\1\207\1\5\1\70\4\21\1\66\1\0\1\2\1\27\4\21\1\222\2\0\1\27\1\5\1\233\1"+
    "\5\1\70\3\21\1\227\12\27\1\234\2\0\1\235\1\236\1\27\30\21\4\0\1\100\2\27\1"+
    "\77\42\21\2\227\4\21\2\227\1\21\1\237\3\21\1\227\6\21\1\32\1\174\1\240\1\30"+
    "\1\241\1\115\1\21\1\30\1\240\1\30\1\242\1\243\3\27\1\244\1\27\1\44\1\131\1"+
    "\27\1\245\1\246\1\51\1\247\1\43\1\44\2\27\1\21\1\30\3\21\1\50\2\27\1\0\1\51"+
    "\1\250\1\0\1\251\1\27\1\252\1\41\1\154\1\253\1\31\1\254\1\21\1\255\1\256\1"+
    "\257\2\27\5\21\1\131\116\27\5\21\1\22\5\21\1\22\20\21\1\30\1\260\1\261\1\27"+
    "\4\21\1\37\1\17\7\21\1\44\1\27\1\63\2\21\1\22\1\27\10\22\4\0\5\27\1\44\72"+
    "\27\1\262\3\27\1\42\1\211\1\253\1\30\1\42\11\21\1\22\1\263\1\42\12\21\1\214"+
    "\1\256\4\21\1\227\1\42\12\21\1\22\2\27\3\21\1\50\6\27\170\21\1\227\11\27\71"+
    "\21\1\30\6\27\21\21\1\30\10\27\5\21\1\227\41\21\1\30\2\21\1\5\1\264\2\27\5"+
    "\21\1\164\1\77\1\265\3\21\1\63\12\21\1\177\3\27\1\44\1\21\1\41\14\21\1\266"+
    "\1\115\1\27\1\21\1\50\11\27\1\21\1\267\1\270\2\21\1\54\2\27\1\131\6\21\1\115"+
    "\1\27\1\271\5\21\1\222\1\0\1\51\1\27\1\5\1\165\2\0\1\271\1\52\1\5\1\70\2\21"+
    "\1\66\1\175\2\21\1\164\1\0\1\2\1\27\3\21\1\30\1\101\5\21\1\54\1\0\1\251\1"+
    "\44\1\5\1\165\2\27\1\160\1\272\5\21\1\103\1\100\1\27\1\270\1\273\1\5\1\165"+
    "\2\21\1\22\1\274\6\21\1\206\1\275\1\226\2\27\1\276\1\21\1\54\1\277\1\27\3"+
    "\300\1\27\2\22\22\27\4\21\1\54\1\301\1\5\1\165\64\21\1\115\1\27\2\21\1\22"+
    "\1\302\5\21\1\115\40\27\55\21\1\227\15\21\1\26\4\27\1\22\1\27\1\302\1\303"+
    "\1\21\1\76\1\22\1\174\1\304\15\21\1\26\3\27\1\302\54\21\1\227\2\27\10\21\1"+
    "\41\6\21\5\27\1\21\1\30\2\0\2\27\1\100\1\27\1\137\2\27\1\256\3\27\1\43\1\32"+
    "\20\21\1\305\1\245\1\27\1\5\1\165\1\42\2\21\1\116\1\42\2\21\1\50\1\306\12"+
    "\21\1\22\3\41\1\307\1\310\2\27\1\311\1\21\1\144\2\21\1\22\2\21\1\312\1\21"+
    "\1\227\1\21\1\227\4\27\17\21\1\50\10\27\6\21\1\30\20\27\1\313\20\27\3\21\1"+
    "\30\6\21\1\131\5\27\3\21\1\22\2\27\3\21\1\50\6\27\3\21\1\227\4\21\1\115\1"+
    "\21\1\253\5\27\23\21\1\227\1\5\1\165\52\27\1\227\1\76\4\21\1\37\1\314\2\21"+
    "\1\227\25\27\2\21\1\227\1\27\3\21\1\26\10\27\7\21\1\306\10\27\1\315\1\77\1"+
    "\144\1\42\2\21\1\115\1\121\4\27\3\21\1\30\20\27\6\21\1\227\1\27\2\21\1\227"+
    "\1\27\2\21\1\50\21\27\11\21\1\131\66\27\1\232\6\21\1\0\1\100\3\27\1\125\1"+
    "\5\2\27\1\232\5\21\1\0\1\316\2\27\3\21\1\131\1\5\1\165\1\232\3\21\1\164\1"+
    "\0\1\317\1\5\10\27\1\232\5\21\1\54\1\0\1\320\1\27\1\5\1\165\42\27\1\160\1"+
    "\272\72\27\1\160\1\272\56\27\1\160\1\272\4\27\5\21\1\54\1\0\1\27\1\5\1\165"+
    "\14\27\1\160\1\272\64\27\1\160\1\272\42\27\55\21\1\22\22\27\14\21\1\50\63"+
    "\27\5\21\1\22\72\27\7\21\1\131\4\27\1\160\1\272\34\27\1\160\1\272\64\27\10"+
    "\21\1\30\1\27\1\103\4\0\1\100\1\27\1\63\1\232\1\21\14\27\1\26\153\27\1\321"+
    "\1\322\2\0\1\323\1\2\3\27\1\324\22\27\1\325\67\27\12\21\1\32\10\21\1\32\1"+
    "\326\1\327\1\21\1\330\1\144\7\21\1\37\1\331\2\32\3\21\1\332\1\174\1\41\1\76"+
    "\51\21\1\227\3\21\1\76\2\21\1\214\3\21\1\214\2\21\1\32\3\21\1\32\2\21\1\22"+
    "\3\21\1\22\3\21\1\76\3\21\1\76\2\21\1\214\1\333\6\5\1\144\3\21\1\166\1\42"+
    "\1\214\1\334\1\252\1\335\1\166\1\237\1\166\2\214\1\124\1\21\1\36\1\21\1\115"+
    "\1\336\1\36\1\21\1\115\50\27\32\21\1\22\5\27\106\21\1\30\1\27\33\21\1\227"+
    "\74\27\1\123\3\27\14\0\20\27\36\0\2\27");

  /* The ZZ_CMAP_A table has 1784 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\2\1\11\1\3\2\11\1\3\6\2\4\0\1\11\1\26\2\0\1\1\2\0\1\5\1\17\1\20\1\21\1"+
    "\0\1\13\1\4\1\14\1\0\12\10\1\15\1\16\1\22\1\23\1\24\1\25\1\0\1\36\1\52\1\34"+
    "\1\37\1\32\1\53\1\45\1\56\1\40\1\54\1\57\1\33\1\46\1\41\1\42\1\60\1\1\1\50"+
    "\1\31\1\35\1\43\1\44\1\55\1\47\1\51\1\1\1\0\1\6\2\0\1\1\1\47\1\51\1\1\1\27"+
    "\1\0\1\30\1\0\6\2\1\12\2\2\1\11\1\0\4\1\4\0\1\1\2\0\1\2\7\0\1\1\4\0\1\1\5"+
    "\0\17\1\1\0\2\40\15\1\1\31\2\1\4\0\4\1\16\0\5\1\7\0\1\1\1\0\1\1\1\0\5\1\1"+
    "\0\2\1\2\0\4\1\10\0\1\1\1\0\3\1\1\0\1\1\1\0\4\1\1\0\13\1\1\0\3\1\1\0\5\2\2"+
    "\0\6\1\1\0\7\1\1\0\1\1\15\0\1\1\1\0\15\2\1\0\1\2\1\0\2\2\1\0\2\2\1\0\1\2\3"+
    "\1\5\0\5\2\6\0\1\1\4\0\3\2\5\0\3\1\5\2\2\10\4\0\2\1\1\2\13\1\1\0\1\1\7\2\2"+
    "\1\2\2\1\0\4\2\2\1\2\10\3\1\2\0\1\1\7\0\1\2\1\1\1\2\6\1\3\2\2\0\11\1\3\2\1"+
    "\1\6\0\2\10\6\1\4\2\2\1\2\0\2\2\1\1\11\2\1\1\3\2\1\1\5\2\2\0\1\1\3\2\4\0\1"+
    "\1\1\0\6\1\4\0\13\2\1\0\4\2\6\1\3\2\1\1\2\2\1\1\7\2\2\1\2\2\2\0\2\10\1\0\3"+
    "\2\1\0\10\1\2\0\2\1\2\0\6\1\1\0\1\1\3\0\4\1\2\0\1\2\1\1\7\2\2\0\2\2\2\0\3"+
    "\2\1\1\5\0\2\1\1\0\5\1\4\0\3\1\4\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1\2\0\1\2\1\0"+
    "\5\2\4\0\2\2\2\0\3\2\3\0\1\2\7\0\4\1\1\0\1\1\7\0\2\10\2\2\3\1\1\2\2\0\1\1"+
    "\1\0\2\1\1\0\3\1\2\2\1\0\3\2\2\0\1\1\15\0\2\2\2\0\1\2\1\1\1\0\6\1\3\0\3\1"+
    "\1\0\4\1\3\0\2\1\1\0\1\1\1\0\2\1\3\0\2\1\3\0\2\1\4\0\5\2\3\0\3\2\1\0\4\2\2"+
    "\0\1\1\6\0\1\2\4\1\1\0\5\1\3\0\1\1\7\2\1\0\2\2\5\0\2\2\3\0\2\2\1\0\3\1\1\0"+
    "\2\1\5\0\3\1\2\0\1\1\3\2\1\0\4\2\1\1\1\0\4\1\1\0\1\1\4\0\1\2\4\0\6\2\1\0\1"+
    "\2\7\0\12\7\2\0\2\2\4\0\1\1\1\2\2\1\7\2\4\0\10\1\1\2\2\10\7\0\2\1\1\0\1\1"+
    "\2\0\2\1\1\0\1\1\2\0\1\1\6\0\4\1\1\0\3\1\1\0\1\1\1\0\1\1\2\0\2\1\1\0\3\1\2"+
    "\2\1\0\2\2\1\1\2\0\5\1\1\0\1\1\1\0\6\2\2\0\2\10\2\0\4\1\2\2\13\0\1\2\1\0\1"+
    "\2\1\0\1\2\4\0\2\2\5\1\3\2\6\0\1\2\1\0\7\2\1\1\2\2\4\1\3\2\1\1\3\2\2\1\7\2"+
    "\3\1\4\2\5\1\14\2\1\1\1\2\2\10\4\2\2\0\3\1\1\0\7\1\2\0\3\2\1\11\11\1\3\2\3"+
    "\0\2\1\2\2\4\0\1\1\1\0\2\2\4\0\4\1\10\2\3\0\1\1\3\0\2\1\1\2\5\0\3\2\2\0\1"+
    "\1\1\2\1\1\5\0\6\1\2\0\5\2\3\1\3\0\10\2\5\1\2\10\3\0\3\1\3\2\1\0\5\2\4\1\1"+
    "\2\4\1\3\2\2\1\2\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1\2\0\3\1\1\0\6\1\2\0\2\1\13"+
    "\11\5\2\2\11\5\2\1\11\4\0\1\1\12\0\1\11\2\0\6\2\1\0\1\2\3\0\4\2\11\0\1\1\4"+
    "\0\1\1\1\0\5\1\2\0\1\1\1\0\1\57\3\1\1\0\3\1\2\0\4\1\5\0\5\1\4\0\1\1\4\0\4"+
    "\1\3\2\2\1\4\0\1\11\4\0\3\1\1\0\2\2\2\0\3\1\2\10\2\1\4\0\6\2\1\0\2\1\2\0\4"+
    "\1\1\0\2\1\1\2\3\1\1\2\4\1\1\2\4\1\2\2\6\1\2\7\6\0\4\1\2\2\4\0\1\1\1\2\4\0"+
    "\1\2\5\1\2\2\3\0\3\1\4\0\3\1\2\2\2\0\6\1\1\0\3\2\1\0\2\2\5\0\5\1\5\0\1\1\1"+
    "\2\3\1\1\0\2\1\1\0\7\1\2\0\1\2\6\0\2\1\2\0\3\1\3\0\2\1\3\0\2\1\2\0\3\2\4\0"+
    "\3\1\1\0\2\1\1\0\1\1\5\0\1\2\2\0\1\1\3\0\1\1\2\0\2\1\3\2\1\0\2\2\1\0\3\2\2"+
    "\0\1\2\2\0\5\2\1\0\2\10\1\2\4\1\10\0\5\2\3\0\6\2\2\0\3\2\2\0\4\2\4\0\3\2\5"+
    "\0\1\1\2\0\2\1\2\0\4\1\1\0\4\1\1\0\1\1\1\0\6\1\2\0\5\1\1\0\4\1\1\0\4\1\2\0"+
    "\2\10\1\0\1\1\1\0\1\1\5\0\1\1\1\0\1\1\1\0\3\1\1\0\3\1\1\0\3\1");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\21\2\1\24\2\4"+
    "\1\25\1\26\1\27\1\30\1\31\11\2\1\32\5\2"+
    "\1\33\2\2\1\34\1\35\5\2\1\36\7\2\1\37"+
    "\7\2\1\40\1\41\1\42\1\43\1\44\2\2\1\45"+
    "\4\2\1\46\1\47\7\2\1\50\2\2\1\51\1\52"+
    "\2\2\1\53\1\54\1\2\1\55\6\2\1\56\1\57"+
    "\2\2\1\60\2\2\1\61\1\2\1\62\1\63\1\64"+
    "\1\65\1\2\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\3\2\1\74\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\61"+
    "\0\61\0\61\0\61\0\61\0\61\0\61\0\u0157\0\61"+
    "\0\u0188\0\61\0\61\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d"+
    "\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405"+
    "\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\61"+
    "\0\u058d\0\61\0\61\0\61\0\61\0\61\0\u05be\0\u05ef"+
    "\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777"+
    "\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\142\0\u089d\0\u08ce"+
    "\0\142\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4\0\142"+
    "\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\142"+
    "\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2\0\142"+
    "\0\142\0\142\0\142\0\142\0\u0cd3\0\u0d04\0\142\0\u0d35"+
    "\0\u0d66\0\u0d97\0\u0dc8\0\142\0\142\0\u0df9\0\u0e2a\0\u0e5b"+
    "\0\u0e8c\0\u0ebd\0\u0eee\0\u0f1f\0\142\0\u0f50\0\u0f81\0\142"+
    "\0\142\0\u0fb2\0\u0fe3\0\142\0\142\0\u1014\0\u1045\0\u1076"+
    "\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b\0\142\0\142\0\u119c"+
    "\0\u11cd\0\142\0\u11fe\0\u122f\0\142\0\u1260\0\142\0\142"+
    "\0\142\0\142\0\u1291\0\142\0\142\0\142\0\142\0\142"+
    "\0\142\0\u12c2\0\u12f3\0\u1324\0\142\0\142";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\2\2\7"+
    "\2\4\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\3\1\41\1\42\3\3\1\43\1\44"+
    "\1\45\1\46\3\3\62\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\30\3\3\0\1\4\5\0\2\4\52\0"+
    "\1\47\54\0\3\6\1\0\1\6\1\50\1\51\52\6"+
    "\7\0\2\7\73\0\1\52\1\53\57\0\1\54\64\0"+
    "\1\55\61\0\1\56\31\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\1\3\1\57\7\3\1\60\1\61\15\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\13\3"+
    "\1\62\2\3\1\63\11\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\5\3\1\64\1\3\1\65\20\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\11\3"+
    "\1\66\16\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\17\3\1\67\10\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\1\70\1\3\1\71\5\3\1\72"+
    "\2\3\1\73\14\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\1\3\1\74\5\3\1\75\20\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\1\76\27\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\11\3"+
    "\1\77\1\100\15\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\10\3\1\101\6\3\1\102\10\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\10\3\1\103"+
    "\17\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\17\3\1\104\10\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\5\3\1\105\1\3\1\106\20\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\1\3\1\107"+
    "\16\3\1\110\7\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\5\3\1\111\1\3\1\112\7\3\1\113"+
    "\10\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\11\3\1\114\16\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\25\3\1\115\2\3\3\47\1\0\55\47"+
    "\3\6\1\0\55\6\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\2\3\1\116\25\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\15\3\1\117\12\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\15\3\1\120"+
    "\12\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\1\3\1\121\26\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\7\3\1\122\20\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\1\123\27\3\1\0\2\3"+
    "\5\0\1\3\1\0\1\3\16\0\26\3\1\124\1\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\10\3"+
    "\1\125\1\3\1\126\15\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\12\3\1\127\15\3\1\0\2\3"+
    "\5\0\1\3\1\0\1\3\16\0\3\3\1\130\24\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\2\3"+
    "\1\131\25\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\6\3\1\132\11\3\1\133\7\3\1\0\2\3"+
    "\5\0\1\3\1\0\1\3\16\0\14\3\1\134\13\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\1\135"+
    "\27\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\1\136\27\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\4\3\1\137\23\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\2\3\1\140\25\3\1\0\2\3"+
    "\5\0\1\3\1\0\1\3\16\0\6\3\1\141\21\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\7\3"+
    "\1\142\20\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\11\3\1\143\16\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\16\3\1\144\11\3\1\0\2\3"+
    "\5\0\1\3\1\0\1\3\16\0\10\3\1\145\17\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\4\3"+
    "\1\146\23\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\2\3\1\147\25\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\17\3\1\150\10\3\1\0\2\3"+
    "\5\0\1\3\1\0\1\3\16\0\11\3\1\151\16\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\7\3"+
    "\1\152\20\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\1\3\1\153\26\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\1\3\1\154\26\3\1\0\2\3"+
    "\5\0\1\3\1\0\1\3\16\0\1\3\1\155\26\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\17\3"+
    "\1\156\10\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\1\157\27\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\4\3\1\160\23\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\1\3\1\161\26\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\3\3\1\162"+
    "\24\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\10\3\1\163\17\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\1\3\1\164\26\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\3\3\1\165\24\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\4\3\1\166"+
    "\23\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\2\3\1\167\25\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\1\3\1\170\26\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\11\3\1\171\16\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\12\3\1\172"+
    "\15\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\24\3\1\173\3\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\1\174\27\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\1\175\27\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\15\3\1\176\12\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\10\3\1\177"+
    "\17\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\17\3\1\200\10\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\3\3\1\201\24\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\20\3\1\202\7\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\4\3\1\203"+
    "\23\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\5\3\1\204\22\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\4\3\1\205\23\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\7\3\1\206\20\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\1\207\27\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\17\3"+
    "\1\210\10\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\10\3\1\211\17\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\27\3\1\212\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\1\3\1\213\26\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\1\3\1\214"+
    "\26\3\1\0\2\3\5\0\1\3\1\0\1\3\16\0"+
    "\4\3\1\215\23\3\1\0\2\3\5\0\1\3\1\0"+
    "\1\3\16\0\1\3\1\216\26\3\1\0\2\3\5\0"+
    "\1\3\1\0\1\3\16\0\4\3\1\217\23\3\1\0"+
    "\2\3\5\0\1\3\1\0\1\3\16\0\1\220\27\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\4\3"+
    "\1\221\23\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\10\3\1\222\17\3\1\0\2\3\5\0\1\3"+
    "\1\0\1\3\16\0\1\3\1\223\26\3\1\0\2\3"+
    "\5\0\1\3\1\0\1\3\16\0\3\3\1\224\24\3"+
    "\1\0\2\3\5\0\1\3\1\0\1\3\16\0\10\3"+
    "\1\225\17\3\1\0\2\3\5\0\1\3\1\0\1\3"+
    "\16\0\4\3\1\226\23\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4949];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\7\11\1\1\1\11\1\1\2\11"+
    "\24\1\1\11\1\1\5\11\150\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FlexibleSearchLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
        return;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return TokenType.BAD_CHARACTER;
            }
          case 62: break;
          case 2: 
            { return IDENTIFIER;
            }
          case 63: break;
          case 3: 
            { return WHITE_SPACE;
            }
          case 64: break;
          case 4: 
            { return STRING;
            }
          case 65: break;
          case 5: 
            { return NUMBER;
            }
          case 66: break;
          case 6: 
            { return COMMA;
            }
          case 67: break;
          case 7: 
            { return DOT;
            }
          case 68: break;
          case 8: 
            { return COLON;
            }
          case 69: break;
          case 9: 
            { return SEMICOLON;
            }
          case 70: break;
          case 10: 
            { return LEFT_PAREN;
            }
          case 71: break;
          case 11: 
            { return RIGHT_PAREN;
            }
          case 72: break;
          case 12: 
            { return ASTERISK;
            }
          case 73: break;
          case 13: 
            { return LESS_THAN_OPERATOR;
            }
          case 74: break;
          case 14: 
            { return EQUALS_OPERATOR;
            }
          case 75: break;
          case 15: 
            { return GREATER_THAN_OPERATOR;
            }
          case 76: break;
          case 16: 
            { return QUESTION_MARK;
            }
          case 77: break;
          case 17: 
            { return EXCLAMATION_MARK;
            }
          case 78: break;
          case 18: 
            { return LEFT_BRACE;
            }
          case 79: break;
          case 19: 
            { return RIGHT_BRACE;
            }
          case 80: break;
          case 20: 
            { return COMMENT;
            }
          case 81: break;
          case 21: 
            { return LESS_THAN_OR_EQUALS_OPERATOR;
            }
          case 82: break;
          case 22: 
            { return NOT_EQUALS_OPERATOR;
            }
          case 83: break;
          case 23: 
            { return GREATER_THAN_OR_EQUALS_OPERATOR;
            }
          case 84: break;
          case 24: 
            { return LEFT_DOUBLE_BRACE;
            }
          case 85: break;
          case 25: 
            { return RIGHT_DOUBLE_BRACE;
            }
          case 86: break;
          case 26: 
            { return AS;
            }
          case 87: break;
          case 27: 
            { return IS;
            }
          case 88: break;
          case 28: 
            { return ON;
            }
          case 89: break;
          case 29: 
            { return OR;
            }
          case 90: break;
          case 30: 
            { return BY;
            }
          case 91: break;
          case 31: 
            { return SUM;
            }
          case 92: break;
          case 32: 
            { return ASC;
            }
          case 93: break;
          case 33: 
            { return ALL;
            }
          case 94: break;
          case 34: 
            { return AND;
            }
          case 95: break;
          case 35: 
            { return ANY;
            }
          case 96: break;
          case 36: 
            { return AVG;
            }
          case 97: break;
          case 37: 
            { return NOT;
            }
          case 98: break;
          case 38: 
            { return MAX;
            }
          case 99: break;
          case 39: 
            { return MIN;
            }
          case 100: break;
          case 40: 
            { return SOME;
            }
          case 101: break;
          case 41: 
            { return LAST;
            }
          case 102: break;
          case 42: 
            { return LIKE;
            }
          case 103: break;
          case 43: 
            { return TRUE;
            }
          case 104: break;
          case 44: 
            { return DESC;
            }
          case 105: break;
          case 45: 
            { return NULL;
            }
          case 106: break;
          case 46: 
            { return FROM;
            }
          case 107: break;
          case 47: 
            { return JOIN;
            }
          case 108: break;
          case 48: 
            { return EVERY;
            }
          case 109: break;
          case 49: 
            { return COUNT;
            }
          case 110: break;
          case 50: 
            { return NULLS;
            }
          case 111: break;
          case 51: 
            { return ORDER;
            }
          case 112: break;
          case 52: 
            { return UNION;
            }
          case 113: break;
          case 53: 
            { return GROUP;
            }
          case 114: break;
          case 54: 
            { return FALSE;
            }
          case 115: break;
          case 55: 
            { return FIRST;
            }
          case 116: break;
          case 56: 
            { return WHERE;
            }
          case 117: break;
          case 57: 
            { return SELECT;
            }
          case 118: break;
          case 58: 
            { return EXISTS;
            }
          case 119: break;
          case 59: 
            { return CONCAT;
            }
          case 120: break;
          case 60: 
            { return BETWEEN;
            }
          case 121: break;
          case 61: 
            { return DISTINCT;
            }
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
